### ISSUE TITLE
Redirect to referrer

### ISSUE THREAD

**Issue by alevor657** [canax/response#1]
Jag tror att det skulle vara värt att lägga till en funktion som gör redirect till den adressen som finns i $_SERVER['HTTP_REFERER']
Det kan användas vid t. ex. formulärhantering.
Vad tycks?

**Comment by mosbth** [comment]
Tanken är att göra en redirect till den sidan som användaren senast besökte? 

Jag kan se att det är en användbar metod. lite i stil med [ResponseUtility::redirectToSelf()`](https://github.com/canax/response/blob/master/src/Response/ResponseUtility.php#L32-L41).

Man behöver vara medveten om att man inte kan lita på innehållet i `$_SERVER['HTTP_REFERER']` då dess innehåll kan manipuleras och webbläsaren behöver inte sätta det.

I vissa flöden, use cases, så kan jag se att man hellre sparar liknande information i sessionen för att minnas vilken sida man skall göra redirect till, efter en längre kedja av inlogging/registrering av användare eller liknande.

Har du ett kodexempel där detta är "nödvändigt" och där alternativen är få?

**Comment by alevor657** [comment]
> Tanken är att göra en redirect till den sidan som användaren senast besökte?

Japp, till exempel om användaren klickar på en knapp som gör en GET request t. ex. vid upvoting av en kommentar. Då kan utvecklaren vilja att snabbt och enkelt göra en redirect till den sidan som gjorde requesten. 

redirectToSelf() fungerar lite annorlunda. Den redirectar ju till den urlen som är anropad. 

> I vissa flöden, use cases, så kan jag se att man hellre sparar liknande information i sessionen för att minnas vilken sida man skall göra redirect till

Det fungerar ju, men det innebär lite med "onödig" pyssel med sessionen när själva requesten innehåller det som behövs. 

> Har du ett kodexempel där detta är "nödvändigt" och där alternativen är få?

Jag har följande knapp: `/reply/upvote/44?questionId=42`. Den är där för att upvote'a en kommentar och göra en redirect till sidan för frågan som kommentaren tillhör till. I detta fallet så använder jag query strängen för att veta vart användaren skall gå efter en upvote. 

> Man behöver vara medveten om att man inte kan lita på innehållet i $_SERVER['HTTP_REFERER'] då dess innehåll kan manipuleras och webbläsaren behöver inte sätta det.

Är det en säkerhetsgrej då är det väl inte så nödvändigt. 
Tänker du på paket sniffing? Att någon modifierar $_SERVER['HTTP_REFERER'] on the fly?

**Comment by mosbth** [comment]
När du gör en upvote så är det en uppdatering av webbplatsens state, av databasen, alla sådana updates bör/skall ske av en POST. Om du gör en POST så kan du också skicka ett hidden fält som berättar till vilken sida man skall redirectas till. Då har du full koll på att redirecten blir korrekt och slipper lite på att webbläsaren fyller i HTTP_REFERER.

Så just det användarfallet är inte orimligt, men kan lösas annorlunda.
Så, det är inte helt klockrent, men heller inte helt utrett om det är en bra/dålig grej.

Man kan själv utöka response-klassen, ärva från den som finns och lägga till metoder och byta vilken klass som instansieras i $di. Det kan vara ett sätt att bygga ut sin kod och få mindre kod i kontroller/modeller.

**Comment by alevor657** [comment]
> Om du gör en POST så kan du också skicka ett hidden fält som berättar till vilken sida man skall redirectas till.

Precis, detta är en identisk lösning som inte bryter mot HTTP.
Men kan man då tycka att man bryter mot det semantiska delen i HTML när man skapar en form som inte är en form egentligen för den bara innehåller ett par knappar och inga input fält? 

> Man kan själv utöka response-klassen, ärva från den som finns och lägga till metoder och byta vilken klass som instansieras i $di. Det kan vara ett sätt att bygga ut sin kod och få mindre kod i kontroller/modeller.

Stämmer, tror det fungerar nog bäst för en sådan kontroversiell fall.
